/* eslint-disable max-len, sort-keys */
export default  [
    // { query: 'data availability quarterly trend', lf: 'DOMM' },
    { query: 'data availability split by phase', lf: 'DOMM'},
    { query: 'data availability split by du', lf: 'DOMM'},
    { query: 'data availability breakup', lf: 'DOMM'},
    { query: 'data availability data not available', lf: 'DOMM'}, 
    { query: 'data availability delay in data', lf: 'DOMM'},
    { query: 'data availability study details', lf: 'DOMM'},
    { query: 'global library catalog quarterly trend', lf: 'DOMM'}, 
    { query: 'global library catalog split by study status', lf: 'DOMM'},
    { query: 'global library catalog split by year', lf: 'DOMM'}, 
    { query: 'global library catalog split by phase', lf: 'DOMM'}, 
    { query: 'global library catalog study details', lf: 'DOMM'}, 
    { query: 'overall summary global library catalog', lf: 'DOMM'}, 
    { query: 'overall summary dbl to final stats', lf: 'DOMM'}, 
    { query: 'overall summary dbl to planned outputs', lf: 'DOMM'}, 
    { query: 'vendors', lf: 'UVP'}, 
    { query: 'services', lf: 'UVP'}, 
    { query: 'du', lf: 'UVP'}, 
    { query: 'indications', lf: 'UVP'},
    { query: 'survey', lf: 'UVP'}, 
    { query: 'performance', lf: 'UVP'}, 
    { query: 'vendor segmentation by tier', lf: 'UVP'}, 
    { query: 'vendor segmentation by du', lf: 'UVP'}, 
    { query: 'vendor segmentation by indication', lf: 'UVP'}, 
    { query: 'issues', lf: 'UVP'}, 
  ];